#!/bin/sh
# TODO TEST THIS
#https://www.cyberciti.biz/tips/linux-iptables-how-to-flush-all-rules.html
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -F
iptables -X
iptables -Z
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X
